spring:
  application:
    name: emailnotificationservice
  config:
    import: optional:configserver:http://configservice:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
